### ISSUE TITLE
Docker-compose + Mariadb init db ERROR: Can't initialize batch_readline

### ISSUE THREAD

**Issue by lucableve** [harness/drone#3227]
Hi, I have a strange problem when launching a mariadb container from a docker / compose service image via drone.

**Scaffolding**
SQL
   -init.sql
.drone.yml
docker-compose.yml   

**.drone.yml**
```
name: ERP Services
kind: pipeline
type: docker


#### Stage Develop
steps:
  - name: Run Services
    image: docker/compose:latest
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker-compose down
      - docker-compose rm
      - docker-compose up --detach
    environment:
      MYSQL_ROOT_PASSWORD:
        from_secret: MYSQL_ROOT_PASSWORD
      MYSQL_USER:
        from_secret: MYSQL_USER
      MYSQL_PASSWORD:
        from_secret: MYSQL_PASSWORD
      MYSQL_DATABASE:
        from_secret: MYSQL_DATABASE
      MYSQL_PORT:
        from_secret: MYSQL_PORT
      PMA_PORT:
        from_secret: PMA_PORT
      CLOUD_SERVER_PORT:
        from_secret: CLOUD_SERVER_PORT
      AWS_S3_ACCESS_KEY_ID:
        from_secret: AWS_S3_ACCESS_KEY_ID
      AWS_S3_SECRET_ACCESS_KEY:
        from_secret: AWS_S3_SECRET_ACCESS_KEY
volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - master
  event:
    - push
    - tag
```

**docker-compose.yml**
```
version: "3.8"
services:
  database:
    image: mariadb:latest
    container_name: Mariadb_ERP
    networks:
      - proxynet
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_TCP_PORT: ${MYSQL_PORT}
      MYSQL_UNIX_PORT: ${MYSQL_PORT}
    volumes:
      - ./SQL/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /ERP/mariadb/:/var/lib/mysql
    restart: unless-stopped
    ports:
      - ${MYSQL_PORT}:3306
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=${MYSQL_ROOT_PASSWORD} --execute "SHOW DATABASES;"'
      interval: 3s
      timeout: 1s
      retries: 5
```

Init.sql does not initialize the database and gives me the following error

[Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
ERROR: Can't initialize batch_readline - may be the input source is a directory or a block device.

I noticed that it is created under the ./drone/src folder of folders:
SQL / init.sql /

I can't find the solution, if I launch it directly from localhost everything works perfectly.
Do I have to go and create a build from the mysql image and do an ADD ./SQL?
