### ISSUE TITLE
Port forwarding

### ISSUE THREAD

**Issue by Mootfrost777** [harness/drone#3248]
I have this .drone.yml:
```
kind: pipeline
name: default
type: docker

steps:
  - name: install_requirements
    image: python
    commands:
      - pip install -r requirements.txt
      - python main.py
    ports:
      - port
    expose:
      - 7632
```
I want to start fastapi/uvicorn app, but I need to forward ports(-p 7632:7632 in docker cli) to access the server. What should I do to solve this problem?
