### ISSUE TITLE
Cannot run shell script in .drone.yml

### ISSUE THREAD

**Issue by hasafox** [harness/drone#3287]
I need to split string in .drone.yml using shell script, however drone server return me an error: "missing closing brace", but the shell script can run success in container by bash:latest(version: 5.2). I can't sure it's my wrong shell script in yaml or drone's bug.
This is the simple `.drone.yml` here.
```yaml
name: drone-test
kind: pipeline
type: docker
load: plugin.jsonnet

steps:
  - name: prepare
    image: bash:latest

    commands:
      - var=aaa:bbb
      - > 
        bash -c "
          if [[ $var == aaa ]]; then 
          echo $var
          else
          array=(${var//:/ })
          echo ${array[1]}
          fi
        "
```

If I use this `.drone.yml`, it is ok.
```yaml
name: drone-test
kind: pipeline
type: docker
load: plugin.jsonnet

steps:
  - name: prepare
    image: bash:latest

    commands:
      - var=aaa:bbb
      - > 
        bash -c "
          if [[ $var == aaa ]]; then 
          echo $var
          else
          echo $var
          fi
        "
```

By the way, I don't need **load** but it is warning in GoLand, so I add "load: plugin.jsonnet" in my `.drone.yml`.
