### ISSUE TITLE
Share data between workflows without privileged mode

### ISSUE THREAD

**Issue by ogarcia** [harness/drone#3299]
We start from this example workflow composed of two pipelines, the second one depending on the first one.
```yaml
---
kind: pipeline
name: simulate build

steps:
- name: build
  image: alpine
  commands:
  - echo "Line 1" > file.txt
  - cat file.txt

---
kind: pipeline
name: simulate package

steps:
- name: deploy
  image: alpine
  commands:
  - echo "Line 2" >> file.txt
  - cat file.txt

depends_on:
- simulate build
```

If we run it as is in the first `cat file.txt` it will show `Line 1` and in the second `cat file.txt` it will show `Line 2`. That is, the pipelines are independent and data is not shared between them.

Right now if I wanted to share data between both pipelines I would have to do something like the following.
```yaml
---
kind: pipeline
name: simulate build

steps:
- name: build
  image: alpine
  volumes:
  - name: data
    path: /data
  commands:
  - echo "Line 1" > /data/file.txt
  - cat /data/file.txt

volumes:
- name: data
  host:
    path: /tmp

---
kind: pipeline
name: simulate package

steps:
- name: deploy
  image: alpine
  volumes:
  - name: data
    path: /data
  commands:
  - echo "Line 2" >> /data/file.txt
  - cat /data/file.txt

volumes:
- name: data
  host:
    path: /tmp

depends_on:
- simulate build
```

While this works correctly it has the problem that it requires the repository to be trusted in Drone in order to mount a host volume for use as temporary volume. Also, since it is a standard host mount and not a temporary mount, the volume is not deleted when the workflow is finished running.

It would be very interesting to have some way to share files between different pipelines without the need for the repository to be marked as trusted, without the need to use a volume on the host and using only temporary volumes.
