### ISSUE TITLE
Possible security concern - Drone instance misused for bitcoin mining

### ISSUE THREAD

**Issue by MauriceNino** [harness/drone#3307]
In the last few days, my VPS seemed to be attacked and used for bitcoin mining.

What I recognized happened:
- Some user got himself added to my users list in drone (at least just as a User, not Admin)
- He managed to start a drone container, running a script, without it showing in the UI
- The container was running [this repository](https://github.com/sirdapa/deepcc) (a bitcoin miner, presumably)

Also, I am not the only person having these issues lately, as it seems - [this forum poster here](https://community.harness.io/t/my-server-hacked-with-drone-io/13689) has the same exact problem, 6 days ago, which is also roughly when it started for me.

Did I misconfigure something, and it just happened to collide with another user's issues? Or is there actually a security concern within Drone?

This is my `docker-compose.yml`:

<details>
   <summary>File</summary>

```yml
version: "3.5"

services:
  drone_server:
    image: drone/drone:2
    restart: unless-stopped
    environment:
      - DRONE_TLS_AUTOCERT=false
      - DRONE_AGENTS_ENABLED=true
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
      - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_SERVER_HOST=drone.xxxx.com
      - DRONE_SERVER_PROTO=https
      - DRONE_LOGS_TRACE=true
      - DRONE_USER_CREATE=username:MauriceNino,admin:true
    volumes:
      - data:/data
    expose:
      - "80"
      - "443"
    networks:
      - proxy_net

  drone_runner:
    image: drone/drone-runner-docker:1
    restart: always
    depends_on:
      - drone_server
    environment:
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_RPC_HOST=drone.xxxx.com
      - DRONE_RPC_PROTO=https
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=LINUX_RUNNER
      - DRONE_LOGS_TRACE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "3000"
    networks:
      - proxy_net

volumes:
  data:

networks:
  proxy_net:
    external: true
```
          
</details>
