### ISSUE TITLE
Issue with environment variables in build

### ISSUE THREAD

**Issue by AlexRAYB** [harness/drone#3347]
Hello, 

I'm having an issue with environment variable interpolation in drone CI. 
I want to define an environment variable called VERSION and use it in my build to define a docker tag. 
This variable has to be concatenated with DRONE_COMMIT_BRANCH variable. 
I have tried many thing like putting this variable at the top of the file, using it like $VERSION, $$VERSION or ${VERSION} but nothing works on my side.  
Can you help me, please, figure out what I'm doing wrong ? 

Thanks in advance, 

Alexandre.

```yml
kind: pipeline
type: kubernetes
name: default

environment: 
  DRONE_LOGS_DEBUG: true

platform:
  os: linux
  arch: amd64

steps:
  - name: build and push docker image on IAM registry
    image: git.toto.com/tools/drone-docker-plugin:latest
    privileged: true
    environment:
      VERSION: 0.0.1-SNAPSHOT
      PLUGIN_MTU: 1300
    settings:
      tags:
         - ${DRONE_COMMIT_BRANCH}_$VERSION
         - latest
      username: drone
      dockerfile: Dockerfile
      context: .
      password: password
      repo: git.toto.com/iam/keycloak-ak-sk-spi
      registry: git.toto.com
```
